# Generated by Django 2.2.16 on 2022-10-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221018_1446'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_followings',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_followings'),
        ),
    ]
